### ISSUE TITLE
SSMS 2014 and VS 2013 installer support...

### ISSUE THREAD

**Issue by TaoK** [TaoK/PoorMansTSqlFormatter#119]
@PaulyGlott noted workaround instructions on Twitter:

https://twitter.com/PoorSQL/status/393809596101701632

**Comment by williamfalconeruk** [comment]
is this issue still open, and will it be resolved in the build any time soon? happy to do the workarounds here for the time being...

**Comment by TaoK** [comment]
This was finally delivered today. VS2013 covered with the VSIX package at https://marketplace.visualstudio.com/vsgallery/8ac2424b-80c9-431b-9049-6e7faa70c244 directly, and SSMS 2014 with a new Extension Installer downloadable at http://architectshack.com/PoorMansTSqlFormatter.ashx
