### ISSUE TITLE
Single entry in the undo stack

### ISSUE THREAD

**Issue by joshka** [TaoK/PoorMansTSqlFormatter#120]
When I hit format sql and then undo, all my sql disappears. It seems that the formatter puts a clear and then a paste rather than selecting all and pasting. This is a minor annoyance (but it gets in the way of quickly visually comparing changes using the undo stack).

**Comment by jawn** [comment]
Same here in SSMS with latest add-in version.

**Comment by TaoK** [comment]
Addressed in version 1.6.6 (VS & SSMS add-in and extension), downloadable in the usual places
