### ISSUE TITLE
Add an option to remove spaces between a function's name and its parameter list.

### ISSUE THREAD

**Issue by rickyclarkson** [TaoK/PoorMansTSqlFormatter#129]
Our code style prefers CURRENT_TIMESTAMP() over CURRENT_TIMESTAMP (), i.e., the extra space is bad. Could the formatter please be updated to make that space able to be suppressed?

Thanks!

**Comment by osfancy** [comment]
This no long appears to be an issue. Extra spaces as per this example do get removed after formatting per the current build.

![image](https://cloud.githubusercontent.com/assets/4641921/18413013/deeecba6-776a-11e6-9b63-4bfb1761dc4b.png)

**Comment by TaoK** [comment]
Yep, as noted by @osfancy, the intent is certainly that function parens follow the function name without any spaces in-between. If the SQL is mis-parsed (interpreted as an arbitrary keyword followed by an empty parens expression) then you will get the other result. 

If you have situations where you get this incorrect result, please provide the details. In the meantime I'll close this issue as not reproduceable.
