### ISSUE TITLE
Newline GO statements

### ISSUE THREAD

**Issue by erandros** [TaoK/PoorMansTSqlFormatter#131]
SQL Server Management Studio requires these in a line on its own.

I did the changes manually to newline before and after each GO, but I don't know if they could be considered good code.

**Comment by TaoK** [comment]
2 years later I imagine you don't have much interest in this anymore...

As far as I know "GO" batch separators were always correctly handled by the library (and plugins, demo apps, and now JS library and CLI utility on NPM) - is it possible you were actually reaching out about a different library?
