### ISSUE TITLE
Query not parsed correctly when IF is used as an IIF function

### ISSUE THREAD

**Issue by TomHart** [TaoK/PoorMansTSqlFormatter#134]
I came across this issue on poorsql.com, so I don't know if it's an issue with their site, or the library, but the following query adds 2 extra close brackets at the end, and says there is a syntax error, even though there isn't.

Here's the SQL http://pastebin.com/de8TDAqm

**Comment by albyrock87** [comment]
There is no bug here.
You forgot a "I", it should be "IIF" not "IF" at line:44

**Comment by TaoK** [comment]
Never noticed this issue come in, sorry. What dialect is the SQL you provided (where IF is a function), @TomHart ? Is it an error as @albyrock87 suggested, or is that a feature of your SQL engine's syntax?

**Comment by TaoK** [comment]
Without more detail here, we have to assume it was a mistake.
