### ISSUE TITLE
Installer for SSMS doesn't validate SSMS version while installing

### ISSUE THREAD

**Issue by tusharnpatel** [TaoK/PoorMansTSqlFormatter#136]
- Assure you have installed SSMS **2014**
- download installer for SSMS 
- install PoorSQL tool.
- validate entry into SSMS -> Tools.
- FAILED : entry "Format T-SQL Code" and "T_SQL formatting options...." not found.

WORKAROUND: 
http://stackoverflow.com/questions/23303026/does-the-poor-mans-t-sql-formatting-add-in-for-management-studio-2012-work-in-ma

**Comment by TaoK** [comment]
The latest installer, covering SSMS versions 2014-17, actually does check that you have at least one compatible SSMS version installed. Downloadable at: http://architectshack.com/PoorMansTSqlFormatter.ashx
