### ISSUE TITLE
VS 2015 Support

### ISSUE THREAD

**Issue by and-rej** [TaoK/PoorMansTSqlFormatter#137]
Is it possible to get this working in Visual Studio 2015?

I have tried the workaround of copying the .AddIn file to the C:\ProgramData\Microsoft\VisualStudio\14.0\Addins directory, but no luck.

According to this MSDN page (https://msdn.microsoft.com/en-au/library/dn246938.aspx) Addins are now deprecated in favour of extensions. Could this be why the old workaround doesn't work?

**Comment by TaoK** [comment]
First try at a VS Extension published to the marketplace at https://marketplace.visualstudio.com/vsgallery/8ac2424b-80c9-431b-9049-6e7faa70c244, should in principle work for Visual Studio 2013, 2015 and 2017.

I've only tried 2015, any input is very welcome!!

Version number and "marketing content" leave a lot to be desired, but as far as I know the product itself is "functionally complete" (to the extent the library itself is).

SSMS support is slightly separate (not mediated by marketplace, and needs additional registration hacks), still working on that, see Issues #144 and #143.

**Comment by TaoK** [comment]
All feedback so far suggests it is working. Closing.
