### ISSUE TITLE
SSMS 2014 integration is not working

### ISSUE THREAD

**Issue by VasuInukollu** [TaoK/PoorMansTSqlFormatter#143]
In the tools menu the shortcut is not added. Please see the attachment.

![untitled](https://cloud.githubusercontent.com/assets/8479377/15849468/612197f8-2cb0-11e6-9886-c4c6f49ad881.png)

**Comment by dandrews216** [comment]
http://stackoverflow.com/questions/23303026/does-the-poor-mans-t-sql-formatting-add-in-for-management-studio-2012-work-in-ma

This should help you.  It doesn't work for 2016 though :(

**Comment by VasuInukollu** [comment]
Thanks. I will check.

**Comment by TaoK** [comment]
This is finally fixed/done. Download the new SSMS 2014-17 Extension installer at http://architectshack.com/PoorMansTSqlFormatter.ashx
