### ISSUE TITLE
SSMS 2016 support

### ISSUE THREAD

**Issue by redmondp** [TaoK/PoorMansTSqlFormatter#144]
It apears that the fix for getting poor sql to work in 2014 version would not work with the new 2016 version.
http://dba.stackexchange.com/questions/134196/sql-server-2016-plugins-not-working/134208#134208

http://stackoverflow.com/questions/36881346/does-the-poor-mans-t-sql-formatting-add-in-for-management-studio-2012-work-in-m?answertab=votes#tab-top

Does anyone have the ability to update the version to support the new API?

**Comment by TaoK** [comment]
Thanks to SQLSentry's note at http://blogs.sqlsentry.com/aaronbertrand/plan-explorer-add-in-ssms-2016/, I finally found some solid hints as to what needs to happen at https://msdn.microsoft.com/en-us/library/dn246938%28v=vs.140%29.aspx.

I don't expect to work on this in the very near term, but would of course welcome any pull requests, "me too" requests, encouragement, outrage, etc.

**Comment by TaoK** [comment]
Also see, earlier info, https://sqljudo.wordpress.com/31-days-of-sql-server-management-studio/ssms-day-30-vspackage-and-ssms/ and http://stackoverflow.com/questions/25599748/porting-visual-studio-vspackage-to-ssms-2012-or-2014/38187013#38187013 , and an interesting/relevant aside at http://dba.stackexchange.com/questions/112379/how-to-change-mssql-management-studio-theme

**Comment by LaneDuncan** [comment]
Me, too!  We seriously love this tool, and it'd be great to have it with SSMS 2016.

**Comment by nikitul** [comment]
Me, too! Fast and nice looking formatted code... This tool is a Must !

**Comment by paulhenri** [comment]
Hello,

I'm not promising anything but i am going to try the convertion.

Stay tuned.
Paul-H

**Comment by TaoK** [comment]
FWIW, I'm finally working on this, and making some progress.

**Comment by TaoK** [comment]
And amusingly, now that I understand what needs to happen, I see someone already did most (? or all) of the work a year ago, and I just didn't see the pull request: https://github.com/TaoK/PoorMansTSqlFormatter/pull/145/commits/c1f4b706dbe0e9bac2989d1d02a18a8dcb8465e6)

**Comment by paulhenri** [comment]
I'm desperatly trying to get theses files to test myself if the plugin is working but i can not manage to get files from c1f4b70... Am i just being dumb ?

**Comment by petertirrell** [comment]
This is something I would be interested in, too!

**Comment by dquille** [comment]
Great news TaoK, thanks.

**Comment by HeinziAT** [comment]
Thanks for working on this, we are looking forward to seeing this in SSMS 2016!

**Comment by mika76** [comment]
Also looking forward to this...

**Comment by CZEMacLeod** [comment]
This would be so useful! I love this but have to copy/paste back and forth to N++.
Will this new release also target VS2017?

**Comment by EltonInAtlanta** [comment]
Really looking forward to this.  I've tried using ApexSql's tools in the interim and I'm tired of fighting with them.  This formatter is *just right*,

**Comment by TheOnlyBrien** [comment]
Been using this in SSMS 2014 for many months after finding out I didn't need to copy/paste my SQL into Notepad++ then copy/paste it back into SSMS. Totally awesome.. but now I just installed SSMS 2016, and no go.. can't wait until you've got it ready!! Thanks for the great work on this, love it!

**Comment by mcfea** [comment]
Me Too! Thanks for the fantastic tool :D

**Comment by ttilberg** [comment]
Another me too request. 

Can anyone elaborate on:
>  (currently it's possible to install by copying the Visual Studio extension package folder to the appropriate place, but honestly it's a pain

**Comment by manoharreddyporeddy** [comment]
@TaoK it's been full 6 months you have assigned this to yourself
can you update manual instructions, please?

**Comment by DennisRCampbell** [comment]
Any update?

**Comment by CZEMacLeod** [comment]
Not sure if SSMS is still on 2016 - I am now using v17.1 (although the 'inner' version seems to be V14)

**Comment by nikitul** [comment]
Me, too! (again). 
@TaoK. I didn't switched my SSMS for 2016 only because I didn't have this tool... 
Like I said... is a MUST!

And off topic (trying to bring a smile here)
[PoorMansTSqlFormatter... PoorMansTSqlFormatter...](https://www.youtube.com/watch?v=5RIXZO9Jzk8)

**Comment by n3xus** [comment]
What's the progress on it? I'm still using NPP to format SQLs. Because other tools doesn't work as nicely as PoorMan

**Comment by vbuga** [comment]
Please provide support for SSMS 2016 and VS2017...
This tool is exceptional!

**Comment by steelwil** [comment]
Could you/somebody please explain how to manually install this plug-in SSMS 17.2. I really do not need an installer at this moment.

**Comment by manoharreddyporeddy** [comment]
@steelwil

Couple of workarounds for now here:

1. Install Notepad++, which is open source, only 32bit, a bit older version, where plugin manager exists, install this plugin to use it, this plugin works in Notepad++ as well.
So, copy sql code into Notepad++, format sql, then copy paste to wherever you want.
This is what I did last year.

2. Install Visual Studio Code which is open source runs on all OSes, there seems sql formatter there as well.

**Comment by ericop** [comment]
Bummer that this hasn't worked for years on modern SSMS versions as it sounds like a cool tool and the website http://poorsql.com/ is still very cool. It's obviously a far superior workflow to be able to press Ctrl-k,Ctrl-d, in SSMS to have clean formatting, than to have to visit some web site, paste, click the output tab and re copy back, and go back to SSMS to past back into your `.sql` file.

**Comment by mika76** [comment]
One option is to have the winforms app somewhere close and then just copy paste, format, copy paste back. Works but not nearly as user friendly as having it within the IDE.

**Comment by TaoK** [comment]
This is finally done... New SSMS Extension installer for SSMS 2014-17 available at http://architectshack.com/PoorMansTSqlFormatter.ashx

**Comment by TheOnlyBrien** [comment]
YES!!!!!!! Thank you!

**Comment by ericop** [comment]
@TaoK how do you use the code formatter in SSMS 2017?  What can i do to check that the `PoorMansTSqlFormatterSSMSPackage.Setup.1.6.1.msi` took effect?  I have checked in Tools > Options and nothing stood out to me. Not sure how to remap <kbd>Ctrl</kbd> + <kbd>K</kbd>, <kbd>Ctrl</kbd>+<kbd>D</kbd> to the PoorMansTSqlFormatterSSMSfunctionality.

![image](https://user-images.githubusercontent.com/5218249/31690521-f1d466ee-b360-11e7-9f20-298cec1fd03c.png)

**Comment by TaoK** [comment]
@ericop if the install was successful and you've restarted SSMS, the first two options in the "Tools" menu should be "Format T-SQL" and "Formatting Options". The formatting options dialog should enable you to set a shortcut using the arcane internal Visual Studio shortcut syntax. I don't know whether the keyboard shortcut UI in SSMS 17 can also be used, I really haven't played with that.

If you're having problems with the shortcuts please create a separate issue; if the formatting menu option is not appearing for you at all let's chat here.

**Comment by steelwil** [comment]
Hi 

@TaoK thanks so very much for this!!!! 

@ericop I also had an issue with the shortcuts on 17.3. I had to disable the existing shortcuts and I eventually got it working. Only Tools.FormatTSQLCode should be set

Cheers

**Comment by ericop** [comment]
@TaoK Yeah, sadly I'm not seeing **Format T-SQL** or **Formatting Options** in SSMS 17.3 . I also ran the `PoorMansTSqlFormatterSSMSPackage.Setup.1.6.1.msi` doing the **Repair** but it still is not showing the options.

![image](https://user-images.githubusercontent.com/5218249/31767865-d4e01fb6-b49a-11e7-9e60-0c8403ae3293.png)

![image](https://user-images.githubusercontent.com/5218249/31767878-dd2cd402-b49a-11e7-8efc-1104ba6ff3cc.png)

**Comment by ericop** [comment]
@TaoK Whew, we are good. I uninstalled, then reinstalled and rebooted windows, and now I have the options, and thanks for the guide @steelwil . Now even my keyboard shortcut commands are all fancy.

So Pumped!
![image](https://user-images.githubusercontent.com/5218249/31770032-193cff4a-b4a4-11e7-8052-71c271352930.png)
