### ISSUE TITLE
Notepad++ Crashes When Installing Plugin

### ISSUE THREAD

**Issue by lriffel** [TaoK/PoorMansTSqlFormatter#149]
Notepad++ crashes when I attempt to install the Poor Man's T-SQL Formatter plugin from the plugin manager.  I upgraded to Notepad++ 7.0 (32 bit) and it still has the same problem.  Other plugins install fine.  My OS is 64 Bit Windows 7.

**Comment by heldersepu** [comment]
Same OS here, and Notepad++ v7.1...
Plugin works for me, I install it manually using the link:
http://architectshack.com/GetFile.aspx?Page=PoorMansTSqlFormatter&File=SqlFormatterNppPlugin.1.5.1.zip

**Comment by lriffel** [comment]
@heldersepu Thank you for that, the workaround works for me as well.

**Comment by TaoK** [comment]
There seem to have been some initial issues in NPP 7 that required Plugin Manager updates; I recently tested after updating to the latest NPP and plugin manager, and did not encounter any issues. Please update this issue if anyone has any further problems, otherwise I will close it in a couple weeks.

**Comment by jiaru0123** [comment]
Hi Tao. Could you please help me that I don't know how to install this plugin?

**Comment by TaoK** [comment]
Hi @jiaru0123, sorry I missed your question - the recommended way is:

- Use Notepad++ 32-bit, the default package, not 64-bit. Unfortunately the 64-bit version does not have a plugin manager yet, so installing and maintaining plugins is much more complicated.
- In Notepad++, navigate to Plugins -> Plugin Manager -> Show Plugin Manager
- In the list, find "Poor Man's T-Sql Formatter"
- Select (check) it, and click "Install"
- Allow the plugin manager to restart Notepad++ as requested
- You should now have a Poor Man's T-Sql Formatter submenu in the Plugins menu.

I'm closing this thread now as there do not seem to be any outstanding problems. Please note, if you come across this thread while searching for the standard "Failed to load" - "PoorMansTSqlFormatter.dll is not compatible with the current version of Notepad++. Do you want to remove this plugin from the plugins directory to prevent this message from displaying" message, that the formatter requires .Net 2.0 to be installed - see Issue #157.
