### ISSUE TITLE
NPP Plugin Manager fails to install PMSF

### ISSUE THREAD

**Issue by rockiesmagicnumber** [TaoK/PoorMansTSqlFormatter#161]
I load Plugin Manager, select Poor Man's T-SQL Formatter, and get the error "Installation of Poor Man's T-SQL Formatter failed."

I've tried going to the architectshack site but it is not up "This website is temporarily unavailable, please try again later."

Can anybody offer any help to get this plugin installed?

**Comment by rsidgrea** [comment]
can someone respond to the post please ?

**Comment by manoharreddyporeddy** [comment]
This is really a bad error with no hints.
This happened to atleast 2 team mates.
Reasons:
1. For some notepad++ was not 32 bit
2. For others it was upgrading the notepad++ from About menu
3. For others installing 2 times worked, after exiting notepad++
4. For some on internet it was to do eith .net version mismatch
5. I would uninstall and then delete every trace of notepad++ and then reinstall above trying point 4.

Above are some solutions that worked.

**Comment by Joe084** [comment]
Hi, I am interesting too!
Install fail because the website is in trouble since 1 month
Anyone have the zip file for mirroring ? (SqlFormatterNppPlugin.1.5.1.zip)

**Comment by luiscla27** [comment]
Hi! it seems that the website where the plugin stored is down so this issue wont be fixed until the site goes online again.

TaoK! please at least upload the DLL to the "release" section of GitHub.

Thank you in advice

**Comment by luiscla27** [comment]
BTW.

Here's the 32 bits version of the plug-in:
https://files.fm/u/ku32p94k

Does anyone has the 64 bits version?

Thank you in advice.

**Comment by bgome1** [comment]
I go the same error before the update, but with the new update I get further. I no longer get "Installation of Poor Man's T-SQL Formatter failed." error right away. Now get new error 'An update is available to Plugin Manager. It is *strongly* advised that the Plugin Manager is updated before any other plugin is installed or updated. Would you like to update the Plugin Manager Now?'. I choose yes, then it says that Notepad++ needs to be restarted, I choose yes again. Then it just restarts Notepad++. I go back to the Plugin Manager to install Poor Man's T-SQL Formatter and the error process starts all over again in a loop. 

Side note:  I am on windows 10, I'm not sure if this has anything to do with the issue. I call this out because I was able to install this on my other computer with has windows 7 just yesterday (7/5/2017).

**Comment by VahidN** [comment]
Hi Guys!
Did you know that [VSCode's MS-SQL Addon](https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql) supports SQL formatting, intellisense, syntax highlighting and ... too?

**Comment by TaoK** [comment]
@rockiesmagicnumber, @rsidgrea, @Joe084, @luiscla27 - sorry about the site outage, it took me a while to notice and a while to fix (switched hosts eventually). Should be all set now, new installations should not have any issues.

**Comment by TaoK** [comment]
@luiscla27 about the 64-bit version, as I noted in issue #150, I have it building and working, but the plugin manager is not yet supported on 64-bit so I assume only the hardcore folks are actually trying to use it. If you really want a compiled downloadable version let me know, and I'll add it to the architectshack site.

**Comment by bgome1** [comment]
Yay I worked! TY for fixing the site. It solved my problem! :)

**Comment by TaoK** [comment]
@bgome1 I just encountered the same issue (although the site was back up and working), it seems to be a weird update flow bug in plugin manager. If you say "Yes" to the plugin manager update then it looks like it's doing something, but it restarts NPP with no changes. To resolve the issue, I:

* Went to Plugin Manager in NPP 
* Switched to the "Updates" tab (cwithout doing anything on the "Available" tab)
* Unchecked all the pending updates except "Plugin Manager"
* Clicked "Update"

That seemed to actually update the plugin manager, and after that everything worked normally. 

Hth!

**Comment by TaoK** [comment]
Thanks for the summary @manoharreddyporeddy - as I noted in Issue #157, sadly I'm not sure there's much I can do to improve the error messaging when the plugin fails to load. In this case however it was failing to download, which was more diagnosable :)

**Comment by TaoK** [comment]
@VahidN wow, nice! It's very exciting to finally see a SQL Formatter officially developed/supported by Microsoft!

This clearly calls into question the long-term need for Poor Man's T-SQL Formatter - esp. as it seems to be MIT-licensed. I assume this should mean other uses, such as encapsulation into a library usable for multiple editors etc shouldn't be too hard to achieve?

For the time being however I'll do my best to keep (or resume) supporting Poor Man's T-SQL Formatter. There's a few exciting possibilities, and if nothing else it's long overdue for support of the latest Visual Studio and SSMS versions.

**Comment by luiscla27** [comment]
@TaoK, i switched to NPP 32 bits version so i've not a real need to download it, but ii think the 64 bits versión should be available to anyone who wants to use it :D 

What do you think about uploading the compiled plug-ins to "releases" here on github?

**Comment by TaoK** [comment]
@luiscla27 I'd like to switch *completely* to GitHub, but until I do that, I'd rather keep things in one place.

**Comment by rsidgrea** [comment]
Fixing the site corrected my problem... much appreciated !! Its a great tool....
