### ISSUE TITLE
Pluses removed when using poorsql.com

### ISSUE THREAD

**Issue by tetsuo13** [TaoK/PoorMansTSqlFormatter#165]
Seems that pluses are being stripped from the formatted SQL when using the http://poorsql.com/ web site (my fallback until #144 arrives).

In the **Input SQL** tab enter the following:

```sql
SELECT 'foo' + 'bar'
```

Click on the **Formatted SQL** tab. Receive the following:

```sql
SELECT 'foo' 'bar'
```

**Comment by TaoK** [comment]
Oops - this is clearly an encoding issue with the JS Engine - see, that's why we introduce these things gradually... :)

Should be fixed within a day or two.

**Comment by TaoK** [comment]
In the meantime, uncheck the "Use JS Engine" checkbox and it will work again (unless there's a reliability issue with the serbive and your query never returns...  :( )

**Comment by TaoK** [comment]
Fix published to poorsql.com...
