### ISSUE TITLE
Option to do line wrapping in "more significant" positions, eg before or after comma?

### ISSUE THREAD

**Issue by TaoK** [TaoK/PoorMansTSqlFormatter#173]
Ray Listenbee requests that we avoid breaking between a column definition and its alias in a select clause, eg instead of:

```
   SELECT prod "Product Code", prdesc "Product Description", sum(cpqty) "Product Qty", cpprice "Prod Retail Price", sum(cpqty * cpprice) 
      "Extended Price", sum(CpQty * PrWhsl) "Cost of Goods Sold"
```

do

```
   SELECT prod "Product Code", prdesc "Product Description", sum(cpqty) "Product Qty", cpprice "Prod Retail Price"
, sum(cpqty * cpprice)  "Extended Price", sum(CpQty * PrWhsl) "Cost of Goods Sold"
```

This sounds like a fun challenge, if anyone's up for it :)

**Comment by manoharreddyporeddy** [comment]
yes, it is.
do you know below?
1. which files, roughly get affected?
2. which requirements to be taken care of?
3. how to test if some other functionality is broken or not?

**Comment by TaoK** [comment]
Turns out this is a duplicate of Issue #117
