### ISSUE TITLE
SSMS Addin options: tab order is not correct

### ISSUE THREAD

**Issue by jawn** [TaoK/PoorMansTSqlFormatter#177]
## Steps

1. Start SSMS with the latest add-in installed.
1. Press TAB to navigate to next field.
1. Repeat until you reach the end of the form

![image](https://user-images.githubusercontent.com/1705112/31996044-31f2e648-b987-11e7-921b-c694669635a7.png)

## Expected result:

Tab key takes you to the next field.

## Actual result:

Tab key does not always take you to the next field.

_Let me know if I can help to solve this issue._

**Comment by jawn** [comment]
Note: same applies to stand alone WinForms UI.

**Comment by TaoK** [comment]
Addressed in version 1.6.6 (VS, SSMS & NPP plugin, and Winforms Demo app), downloadable in the usual places.

**Comment by jawn** [comment]
Thanks for the quick update!
