### ISSUE TITLE
[noformat][/noformat] tags are broken

### ISSUE THREAD

**Issue by TaoK** [TaoK/PoorMansTSqlFormatter#182]
@StrayChild01 notes that [noformat][/noformat] comment region markers don't work in VS Code, and it turns out they don't work at all in any of the environments, presumably since the big JS-compatibility refactor in 1.6.*!

**Comment by StrayChild01** [comment]
Hi,

I tested [minify][/minify] and it has the same problem: It deletes everything inside it even if is a comment.
