### ISSUE TITLE
Azure Data Studio support

### ISSUE THREAD

**Issue by svanuden** [TaoK/PoorMansTSqlFormatter#205]
I would like to use the formatter in the new Azure Data Studio.
Can you create a VISX for that as well?

**Comment by TaoK** [comment]
@dzsquared has already done this in a fork, see #208. He's also provided instructions on how to do an install manually, by installing VS Code and copying over the extension folder to the right place for Azure Data Studio, as I'd first outlined on twitter about a year ago before a marketplace even existed (https://twitter.com/PoorSQL/status/932786278684381185). I will make an effort to review and duplicate or integrate his work into an "official" marketplace release if/when possible, but in the meantime you should be all set.
