### ISSUE TITLE
Support for SSMS version 18.0

### ISSUE THREAD

**Issue by Atomahawk** [TaoK/PoorMansTSqlFormatter#206]

**Comment by dsolodow** [comment]
Any updates here now that RC1 is out?

**Comment by D34d3nd** [comment]
I wanted to upvote this and check in on if this will be updated for SSMS 18.0 as well. 18.0 is in GA now since April 24, 2019. I dont expect this updated in an instant, just checking if this is on the radar. I dont care for the way other formatting addins do their formatting. This is the best and simplest one.

**Comment by VDMT** [comment]
@Atomahawk @dsolodow @D34d3nd 
A workaround to getting it working on SSMS v18 is by copying "PoorMansTSqlFormatterSSMSPackage.pkgdef" to "C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\Extensions". Re-open v18 and it should appear under Tools.

I had PoorMansTSQLFormatter working on SSMS v17.9, the above .pkgdef is located at: "C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Extensions"

Hope that helps...

**Comment by D34d3nd** [comment]
> @Atomahawk @dsolodow @D34d3nd
> A workaround to getting it working on SSMS v18 is by copying "PoorMansTSqlFormatterSSMSPackage.pkgdef" to "C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\Extensions". Re-open v18 and it should appear under Tools.
> 
> I had PoorMansTSQLFormatter working on SSMS v17.9, the above .pkgdef is located at: "C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Extensions"
> 
> Hope that helps...

Yep, this worked. Thank you very much for this.

**Comment by TaoK** [comment]
Sorry about the delay, I finally got some vacation time this week, the new version is available for download/install!

https://twitter.com/PoorSQL/status/1155471888145141761
