### ISSUE TITLE
Notepad ++ new system for plugins (Plugins Admin)

### ISSUE THREAD

**Issue by PeterDeKeer** [TaoK/PoorMansTSqlFormatter#212]
Hi, I just wanted to let you know that I really apreciate you to have done this!

I just noticed that there is a new way for plugins to get installed in a official notepad++ update system:
https://notepad-plus-plus.org/features/plugin-admin.html

I would love to see your plugin there!

**Comment by databasekevin** [comment]
Please, please, please!

**Comment by TaoK** [comment]
@StrayChild01 - the *manual* method needs to be updated based on Notepad++'s new plugin-loading behavior as of 7.6. I'll update the manual instructions on the site. 

The correct manual install instructions are:

- If your Notepad++ version is 7.6, then **upgrade**. This version has an inconsistent (later changed) plugin location.
  - The latest version can be downloaded at https://notepad-plus-plus.org/news/
  - Once you have version 7.6.1 or later, continue
- Navigate to `%PROGRAMDATA%\Notepad++\plugins\`, eg by pressing Win+r, and pasting it in. On my computer, I end up in `C:\ProgramData\Notepad++\plugins`.
- Create a new folder called "PoorMansTSqlFormatterNppPlugin" there.
- Unzip the entire contents of the ZIP file (1 DLL + 1 folder containing other DLLs and stuff) into there
  - (or move the "PoorMansTSqlFormatterNppPlugin.dll" file and "PoorMansTSqlFormatterNppPlugin" folder from where it would have been in a previous version, at %PROGRAMFILES%\Notepad++\plugins\)

-> Now the next time you start Notepad++, you should find the plugin installed and working.

Next, I'll see about getting set up in the new plugin admin.

**Comment by TaoK** [comment]
The plugin should appear in the new plugin manager (64-bit and 32-bit versions) shortly - as soon as the relevant Pull Request on the plugin list project is accepted: notepad-plus-plus/nppPluginList#51

**Comment by databasekevin** [comment]
@TaoK Still unable to see the menu plugin (or use PoorSQLformatter) even after following directions above. Just to make sure, there is a "new" folder creation called "PoorMansTSqlFormatterNppPlugin" and inside of that folder is two items:

1. PoorMansTSqlFormatterNppPlugin [folder filled with DLL's]
2.* PoorMansTSqlFormatterNppPlugin.dll

on 64 Bit Notepad++ and downloaded that Zip for reference.

**Comment by StrayChild01** [comment]
> 
> 
> Still unable to see the menu plugin (or use PoorSQLformatter) even after following directions above. Just to make sure, there is a "new" folder creation called "PoorMansTSqlFormatterNppPlugin" and inside of that folder is two items:
> 
>     1. PoorMansTSqlFormatterNppPlugin [folder filled with DLL's]
> 
>     2. PoorMansTSqlFormatterNppPlugin.dll
> 
> 
> on 64 bit Notepad++ 7.6.3 and downloaded the 64 bit * PoorMansTSqlFormatterNppPlugin Zip for reference.

Hey, @databasekevin So I updated to the newest version and the plugin dissapeared, I followed these instructions and it worked:

  - For Notepad++ 7.6.3 and later, if properly installed via installer, create a new folder called "PoorMansTSqlFormatterNppPlugin" in your Notepad++ install folder's "plugins" subfolder, eg "C:\Program Files\Notepad++\plugins\PoorMansTSqlFormatterNppPlugin", and unzip the entire contents of the ZIP file (1 DLL + 1 folder containing other DLLs and stuff) into this new subfolder. It's almost the same as before 7.6, except now the contents of the ZIP file ned to be in a correctly-named subfolder, not directly in the plugins folder.

    If you've got a "portable" Notepad++ setup, then the old approach (unzip the entire contents of the ZIP file (1 DLL + 1 folder containing other DLLs and stuff) into your Notepad++ install folder's "plugins" subfolder) should still be the right thing.

You might need to use PowerShell as administrator and extract it using `Extract-Archive SqlFormatterNppPlugin.x64.1.6.10.b.zip . ` I did it this way.

**Comment by TaoK** [comment]
Hi, the latest version of Notepad++, 7.6.4, released today, includes Poor Man's T-Sql formatter in the plugin admin list. Closing.

**Comment by StrayChild01** [comment]
Thanks! I installed the new version and I can see it there!
