### ISSUE TITLE
For temporary table names, i.e. #tableName, the # and the tableName are separated with a space

### ISSUE THREAD

**Issue by erapade** [TaoK/PoorMansTSqlFormatter#216]
As the heading says. temporary table names are not handled correctly:

For
CREATE TABLE #calendardst ([year] INT PRIMARY KEY)

The formatted code looks like below
CREATE TABLE # calendardst (
	[year] INT PRIMARY KEY
	);

Please note the space between # and the tableName. 
This also happens on all references to the table name

**Comment by TaoK** [comment]
I can't reproduce this eg on poorsql.com, eg:

https://poorsql.com/?inputString=CREATE+TABLE+%23calendardst+(%5Byear%5D+INT+PRIMARY+KEY)

Do you have a more specific reproduction case? Is the issue presenting in a particular tool?

**Comment by erapade** [comment]
I tried to reproduce in Azure Data Studio (the tool i think I used before), but I can't reproduce the fault either, so I close this ticket.
