### ISSUE TITLE
Extension for SSMS 2019

### ISSUE THREAD

**Issue by tuzzu** [TaoK/PoorMansTSqlFormatter#220]
Hi, I've fixed the dependencies to allow working with Visualstudio 2019 and SSMS 18.0.
I have not touched the source code but only the project file.
Operation:
1) Complete the project.
2) Copy the file PoorMansTSqlFormatterSSMSPackage.pkgdef to the directory: C: Program Files (x86) SQL Server Management Studio 18 Common7 IDE Extensions
3) Modify the file PoorMansTSqlFormatterSSMSPackage.pkgdef replacing "CodeBase" = "C: XXX with the solution path
4) Start SSMS 18.0

Project File: 
[PoorMansTSqlFormatter.zip](https://github.com/TaoK/PoorMansTSqlFormatter/files/3260393/PoorMansTSqlFormatter.zip)

PoorMansTSqlFormatterSSMSPackage.pkgdef:
[PoorMansTSqlFormatterSSMSPackage.zip](https://github.com/TaoK/PoorMansTSqlFormatter/files/3260398/PoorMansTSqlFormatterSSMSPackage.zip)

**Comment by TaoK** [comment]
Sorry about the delay, I finally got some vacation time this week, the new version is available for download/install!

Sorry about the delay, I finally got some vacation time this week, the new version is available for download/install!

https://twitter.com/PoorSQL/status/1155471888145141761
