### ISSUE TITLE
Cannot get version 1.6.13 installed

### ISSUE THREAD

**Issue by steelwil** [TaoK/PoorMansTSqlFormatter#226]
I tried upgrading, but SSMS 18.2 says that there is an issue loading the extension and the menu options are greyed out, SSMS 17.9 menu items are greyed out.

I uninstalled everything, reinstalled and I get the same issue.

I then reloaded 1.6.11 and everything worked, just had to do the copy of the pkgdef file for 18.2

My Windows 10 version is 1903

**Comment by TaoK** [comment]
Thanks for the fast and clear feedback, and sorry I screwed up the installer. Fixed as 1.6.13b. Fix announced on twitter. Same issue noted in #227. Let me know if any further problems!
