### ISSUE TITLE
This extension is already installed to all applicable products.

### ISSUE THREAD

**Issue by spottedmahn** [TaoK/PoorMansTSqlFormatter#231]
![image](https://user-images.githubusercontent.com/14079228/62215903-ca69fd00-b375-11e9-9afd-6451e2c7a28c.png)

>This extension is already installed to all applicable products.

FYI, the upgrade [from 1.6.13 to 1.6.14](https://github.com/TaoK/PoorMansTSqlFormatter/issues/228#issuecomment-516535550) is failing for me.

I'll try an uninstall and re-install next...

**Comment by TaoK** [comment]
This message is normal if you download the extension VSIX file and run it; Visual Studio's vsix installer doesn't seem to have an upgrade action (in the manual execution UI).

If, on the other hand, you let Visual Studio do the upgrade for you (just go take a look at the extension management area, you should see a message that an extension is being updated normally afaik), it should work fine. 

Alternatively, uninstalling and reinstalling should work too.

Please note, this "installer doesn't automatically upgrade" issue is specific to Visual Studio; The installer for SSMS, on the other hand, handles uninstalling the old version as you install the new one automatically.

**Comment by spottedmahn** [comment]
FYI I did it via the Update option in VS:

![image](https://user-images.githubusercontent.com/14079228/62297938-0d90a280-b440-11e9-9217-158a1b9d63ac.png)

**Comment by spottedmahn** [comment]
Didn't happen w/ this upgrade from 1.6.14 to 1.16.15 😊
