### ISSUE TITLE
Postgresql Json Column Add Spaces

### ISSUE THREAD

**Issue by hugorn** [TaoK/PoorMansTSqlFormatter#289]
Before formating

`select params->>'name' from events;`

After formatting it is adding spaces ->> causing error

`select params - > > 'name' from events;`

Perhaps a parameter that allows you to indicate certain keywords that should not be changed would be a good idea.

**Comment by CZEMacLeod** [comment]
This is designed specifically for the T-SQL variant as used by Microsoft SQL Server. While it probably works okay with generic SQL statements for other databases - they do have differing escape characters and keywords, so I don't think it can really be used for any specific stuff like Postgres Json statements.

**Comment by hugorn** [comment]
What a shame, of all the ones I tested, this was by far the one with the best overall results.

**Comment by crazycga** [comment]
> What a shame, of all the ones I tested, this was by far the one with the best overall results.

Maybe you could help me understand this, but I don't get why you're disappointed that a Microsoft format like an SSRS report doesn't work for non-Microsoft products?  RDL type reports are SSRS specific (unless I'm mistaken?)

**Comment by hugorn** [comment]
All doubts were clarified.
Thank you and I'm already closing this issue
