### ISSUE TITLE
SqlFormatterLibrary_35.1.4.3 demo needed 

### ISSUE THREAD

**Issue by sms0817301** [TaoK/PoorMansTSqlFormatter#94]
demo needed how to use the SqlFormatterLibrary_35.1.4.3 dll in my project.. my requirement is to separate and parse the where clause (where a=b and c=d)

attr name = a
oper = '='
attr name = b
cond = 'and'
.
.
.
.

Its so urgent.. I am in between one task because of this.

**Comment by TaoK** [comment]
Sorry I missed this; I'm going to assume there's not much I can do to help you at this point.
